"""
Shared parsing utilities for Evolution AB buyback press releases.

The HTML structure of an Evolution buyback announcement is the same
regardless of which surface delivers it (Cision newsroom, evolution.com,
Nasdaq attachment archive), because the underlying text is generated by
Evolution's own legal/IR team and distributed via Cision.

This module contains all date/number/text parsing helpers + the master
`parse_buyback_view(html)` function. Source modules just need to fetch
the HTML and pass it in.

The press release follows MAR Article 5 / Reg 2016/1052 weekly format:
  "during the period DD Mon - DD Mon, acquired a total of N own shares"
  + daily table with Date | Volume | Avg price | Transaction value
  + holding statement ("amounted to X as of DD Mon YYYY")
  + total shares statement ("The total number of shares in Evolution is X")
  + max cap ("A maximum of N shares in total may be acquired")
  + program accumulator ("a total of X shares have been acquired within
    the scope of the programme")
  + optional completion flag ("completed and closed" or "thereby completed")
"""

from __future__ import annotations

import re
from datetime import datetime, date
from typing import Optional

from bs4 import BeautifulSoup


# Headlines we recognize as buyback announcements
BUYBACK_HEADLINE_KEYWORDS = (
    "acquisition of own shares",
    "acquisitions of own shares",
    "transaction in own shares",
)


# ============================================================
# Date parsing
# ============================================================

EN_MONTHS = {
    "january": 1, "february": 2, "march": 3, "april": 4,
    "may": 5, "june": 6, "july": 7, "august": 8,
    "september": 9, "october": 10, "november": 11, "december": 12,
}


def parse_iso_date(s: str) -> Optional[date]:
    """Parse 'YYYY-MM-DD' or 'YYYY-MM-DD HH:MM:SS' to date."""
    if not s:
        return None
    s = s.strip().split("T")[0].split(" ")[0]
    try:
        return datetime.strptime(s, "%Y-%m-%d").date()
    except ValueError:
        return None


def parse_en_date(s: str, default_year: Optional[int] = None) -> Optional[date]:
    """Parse '07 May 2026' or '7 May' (year inferred from default_year)."""
    s = s.strip()
    if not s:
        return None
    m = re.match(r"^(\d{1,2})\s+([A-Za-z]+)\s+(\d{4})$", s)
    if m:
        day, month_name, year = int(m.group(1)), m.group(2).lower(), int(m.group(3))
        if month_name in EN_MONTHS:
            try:
                return date(year, EN_MONTHS[month_name], day)
            except ValueError:
                return None
    m = re.match(r"^(\d{1,2})\s+([A-Za-z]+)$", s)
    if m and default_year is not None:
        day, month_name = int(m.group(1)), m.group(2).lower()
        if month_name in EN_MONTHS:
            try:
                return date(default_year, EN_MONTHS[month_name], day)
            except ValueError:
                return None
    return None


def parse_number(s: str) -> Optional[float]:
    """Parse '1,234,567.89' (US format used in Evolution announcements)."""
    if not s:
        return None
    s = s.strip().replace("\xa0", "").replace(" ", "").replace(",", "")
    if not s or s in ("-", "–", "—"):
        return None
    try:
        return float(s)
    except ValueError:
        return None


# ============================================================
# Buyback HTML parser
# ============================================================

def parse_buyback_view(html: str) -> dict:
    """
    Parse an Evolution AB buyback press release into structured data.

    Works on HTML from any surface: Cision, evolution.com IR, etc.
    Returns dict with keys:
      - period_start, period_end (ISO date strings)
      - week_shares, week_amount (totals from daily table), week_avg_price
      - treasury_shares (holding as of period end)
      - total_shares_outstanding
      - max_program_shares (10% cap)
      - acc_shares (cumulative under current program)
      - daily_transactions (list of {date, shares, avg_price, amount})
      - completed (True if announcement signals program closure)
    """
    soup = BeautifulSoup(html, "html.parser")
    text = soup.get_text(" ", strip=True)
    text = re.sub(r"\s+", " ", text)

    result = {
        "period_start": None,
        "period_end": None,
        "week_shares": None,
        "week_amount": None,
        "week_avg_price": None,
        "daily_transactions": [],
        "treasury_shares": None,
        "total_shares_outstanding": None,
        "max_program_shares": None,
        "completed": False,
        "acc_shares": None,
    }

    # ── PERIOD + WEEK SHARES ──
    # Handles both:
    #   "during the period 07 July - 11 July, acquired a total of N own shares"
    #   "during the period 25 May 2026 – 29 May 2026, acquired a total of N own shares"
    # Dash can be hyphen-minus, en-dash, em-dash, or non-breaking hyphen
    m = re.search(
        r"during the period\s+"
        r"(\d{1,2}\s+[A-Za-z]+(?:\s+\d{4})?)"
        r"\s*[\-\u2010\u2011\u2012\u2013\u2014\u2015]\s*"
        r"(\d{1,2}\s+[A-Za-z]+(?:\s+\d{4})?)"
        r".*?acquired a total of\s+([\d,]+)\s+own shares",
        text, re.IGNORECASE | re.DOTALL
    )
    if not m:
        return result

    start_str, end_str, shares_str = m.group(1), m.group(2), m.group(3)
    result["week_shares"] = int(shares_str.replace(",", ""))

    # ── COMPLETION FLAG ──
    if re.search(
        r"completed and closed|thereby completed|repurchase program(?:me)? is thereby",
        text, re.IGNORECASE
    ):
        result["completed"] = True

    # ── TREASURY HOLDING (also gives us the year for the period dates) ──
    m_hold = re.search(
        r"holding of own shares amounted to\s+([\d,]+)\s+as of\s+(\d{1,2}\s+[A-Za-z]+\s+\d{4})",
        text, re.IGNORECASE
    )
    holding_year = None
    if m_hold:
        result["treasury_shares"] = int(m_hold.group(1).replace(",", ""))
        end_date = parse_en_date(m_hold.group(2))
        if end_date:
            holding_year = end_date.year

    # Resolve period dates using year from "as of" clause OR from start/end strings themselves
    if holding_year:
        ps = parse_en_date(start_str, default_year=holding_year)
        pe = parse_en_date(end_str, default_year=holding_year)
    else:
        # Try parsing without default year (in case start/end already contain year)
        ps = parse_en_date(start_str)
        pe = parse_en_date(end_str)
        # If still missing year, try inferring from any year in end_str/start_str
        if not pe:
            year_match = re.search(r"\b(20\d{2})\b", start_str + " " + end_str)
            if year_match:
                yr = int(year_match.group(1))
                ps = parse_en_date(start_str, default_year=yr)
                pe = parse_en_date(end_str, default_year=yr)
    if ps:
        result["period_start"] = ps.isoformat()
    if pe:
        result["period_end"] = pe.isoformat()

    # ── TOTAL SHARES OUTSTANDING ──
    m = re.search(
        r"total number of shares in Evolution is\s+([\d,]+)",
        text, re.IGNORECASE
    )
    if m:
        result["total_shares_outstanding"] = int(m.group(1).replace(",", ""))

    # ── MAX PROGRAM SHARES (10% cap) ──
    m = re.search(
        r"[Aa] maximum of\s+([\d,]+)\s+shares in total may be acquired",
        text
    )
    if m:
        result["max_program_shares"] = int(m.group(1).replace(",", ""))

    # ── ACCUMULATED IN CURRENT PROGRAM ──
    m = re.search(
        r"a total of\s+([\d,]+)\s+shares have been acquired within the scope of the (?:programme|program)",
        text, re.IGNORECASE
    )
    if m:
        result["acc_shares"] = int(m.group(1).replace(",", ""))

    # ── DAILY TRANSACTION TABLE ──
    # First try HTML table (works on news.cision.com detail pages)
    for table in soup.find_all("table"):
        head = " ".join(
            c.get_text(" ", strip=True).lower()
            for c in table.find_all(["th", "td"])[:8]
        )
        if "date" in head and "volume" in head and "price" in head:
            for tr in table.find_all("tr"):
                cells = [td.get_text(" ", strip=True) for td in tr.find_all(["td", "th"])]
                if len(cells) < 4:
                    continue
                d = parse_iso_date(cells[0])
                if d is None:
                    continue
                vol = parse_number(cells[1])
                avg = parse_number(cells[2])
                val = parse_number(cells[3])
                if None in (vol, avg, val):
                    continue
                result["daily_transactions"].append({
                    "date": d.isoformat(),
                    "shares": int(vol),
                    "avg_price": round(avg, 4),
                    "amount": int(round(val)),
                })
            if result["daily_transactions"]:
                break  # Found the right table

    # Fallback: if no HTML table found, try text-line parsing (PDF format)
    # Pattern: "YYYY-MM-DD  <shares>  <price>  <amount>" on a single line
    if not result["daily_transactions"]:
        row_re = re.compile(
            r"(\d{4}-\d{2}-\d{2})"           # ISO date
            r"\s+([\d,]+)"                    # shares (integer with commas)
            r"\s+([\d,]+\.\d+)"               # avg price (decimal)
            r"\s+([\d,]+\.\d+)"               # transaction value (decimal)
        )
        for m in row_re.finditer(text):
            d = parse_iso_date(m.group(1))
            if d is None:
                continue
            vol = parse_number(m.group(2))
            avg = parse_number(m.group(3))
            val = parse_number(m.group(4))
            if None in (vol, avg, val):
                continue
            result["daily_transactions"].append({
                "date": d.isoformat(),
                "shares": int(vol),
                "avg_price": round(avg, 4),
                "amount": int(round(val)),
            })

    # Compute week_amount + week_avg_price from daily table
    if result["daily_transactions"]:
        week_amt = sum(t["amount"] for t in result["daily_transactions"])
        week_sh = sum(t["shares"] for t in result["daily_transactions"])
        result["week_amount"] = week_amt
        result["week_avg_price"] = round(week_amt / week_sh, 4) if week_sh else 0.0

    return result
